anchor_version = "0.24.2"

[workspace]
members = ["fairlaunch"]

[provider]
cluster = "mainnet"
url = "https://ssc-dao.genesysgo.net/"
wallet = "~/.config/solana/f3d.json"

[programs.mainnet]
fairlaunch = "4SVNgru9G3ANsHmLFyAEv2H8odpNSqawfSscH8kJtKKX"

[programs.localnet]
fairlaunch = "4SVNgru9G3ANsHmLFyAEv2H8odpNSqawfSscH8kJtKKX"
