[registry]
url = "https://anchor.projectserum.com"

[provider]	  
cluster = "mainnet"
wallet = "~/.config/solana/f3d.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 test/*.ts"

[workspace]
members = ["fair-launch"]
